# (11주차) 5월11일

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈
- editor : 이강철

### imports 

In [1]:
import tensorflow as tf 
import tensorflow.experimental.numpy as tnp

In [2]:
tnp.experimental_enable_numpy_behavior()

In [3]:
import matplotlib.pyplot as plt

### 지난시간요약 

`-` 이미지자료의 정리 

In [4]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
tf.constant(x_train.reshape(-1,28,28,1),dtype=tf.float64).shape
#tf.constant(x_train.reshape(60000,28,28,1),dtype=tf.float64).shape

TensorShape([60000, 28, 28, 1])

In [7]:
X = tf.constant(x_train.reshape(-1,28,28,1),dtype=tf.float64)
y = tf.keras.utils.to_categorical(y_train)
XX = tf.constant(x_test.reshape(-1,28,28,1),dtype=tf.float64)
yy = tf.keras.utils.to_categorical(y_test)

`-` net1,2

In [10]:
tf.random.set_seed(43052)
net1 = tf.keras.Sequential()
net1.add(tf.keras.layers.Flatten()) ## 데이터를 펼치는 과정
net1.add(tf.keras.layers.Dense(30,activation='relu'))
net1.add(tf.keras.layers.Dense(10,activation='softmax'))
net1.compile(loss=tf.losses.categorical_crossentropy,optimizer='adam',metrics='accuracy')
net1.fit(X,y,epochs=10,verbose=0)

In [11]:
net1.evaluate(X,y)

1875/1875 [==============================] - 4s 2ms/step - loss: 0.6145 - accuracy: 0.7520


[0.614452600479126, 0.7520333528518677]

In [12]:
tf.random.set_seed(43052)
net2 = tf.keras.Sequential()
net2.add(tf.keras.layers.Flatten())
net2.add(tf.keras.layers.Dense(500,activation='relu'))
net2.add(tf.keras.layers.Dense(500,activation='relu'))
net2.add(tf.keras.layers.Dense(500,activation='relu'))
net2.add(tf.keras.layers.Dense(500,activation='relu'))
net2.add(tf.keras.layers.Dense(10,activation='softmax'))
net2.compile(loss=tf.losses.categorical_crossentropy,optimizer='adam',metrics='accuracy')
net2.fit(X,y,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 1.1154 - accuracy: 0.7879
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4502 - accuracy: 0.8384
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4117 - accuracy: 0.8536
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3950 - accuracy: 0.8601
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3770 - accuracy: 0.8663
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3625 - accuracy: 0.8713
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3498 - accuracy: 0.8760
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3358 - accuracy: 0.8801
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3328 - accuracy: 0.8817
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.318

In [13]:
net2.evaluate(XX,yy)

313/313 [==============================] - 1s 2ms/step - loss: 0.3804 - accuracy: 0.8655


[0.38036859035491943, 0.8654999732971191]

- DNN 아키텍처로는 한계가 있음
- 파라미터 개수가 늘어난 것에 비해 딱히 성능이 많이 좋아진 것 같지는 않음

`-` net3 : Conv2D + MaxPool2D

In [14]:
tf.random.set_seed(43052)
net3 = tf.keras.Sequential()
net3.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net3.add(tf.keras.layers.MaxPool2D()) # net3.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))와 동일한 코드
net3.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net3.add(tf.keras.layers.MaxPool2D())
net3.add(tf.keras.layers.Flatten())
net3.add(tf.keras.layers.Dense(10,activation='softmax'))
net3.compile(loss=tf.losses.categorical_crossentropy,optimizer='adam',metrics='accuracy')
net3.fit(X,y,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 14s 3ms/step - loss: 0.7710 - accuracy: 0.8084
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3586 - accuracy: 0.8730
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3152 - accuracy: 0.8868
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2940 - accuracy: 0.8935
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2793 - accuracy: 0.8989
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2659 - accuracy: 0.9027
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2573 - accuracy: 0.9063
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2487 - accuracy: 0.9090
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2441 - accuracy: 0.9110
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.23

In [16]:
net3.evaluate(XX,yy)

313/313 [==============================] - 1s 3ms/step - loss: 0.3457 - accuracy: 0.8801


[0.3457203209400177, 0.8801000118255615]

In [22]:
net2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 500)               392500    
                                                                 
 dense_5 (Dense)             (None, 500)               250500    
                                                                 
 dense_6 (Dense)             (None, 500)               250500    
                                                                 
 dense_7 (Dense)             (None, 500)               250500    
                                                                 
 dense_8 (Dense)             (None, 10)                5010      
                                                                 
Total params: 1,149,010
Trainable params: 1,149,010
No

In [21]:
net3.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 27, 27, 30)        150       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 30)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 12, 12, 30)        3630      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 30)         0         
 2D)                                                             
                                                                 
 flatten_3 (Flatten)         (None, 1080)              0         
                                                                 
 dense_9 (Dense)             (None, 10)               

- DNN의 한계(모형이 너무 복잡합)를 가볍게 돌파


`-` net3의 구조 감상

In [23]:
net3.layers

In [24]:
cv1, mp1, cv2, mp2, flttn, d1 = net3.layers

In [25]:
print(XX.shape) ## 이미지 (2D)
print(cv1(XX).shape) ## 이미지 (2D)
print(mp1(cv1(XX)).shape) ## 이미지 (2D)
print(cv2(mp1(cv1(XX))).shape) ## 이미지 (2D) 
print(mp2(cv2(mp1(cv1(XX)))).shape) ## 이미지 (2D) 
print(flttn(mp2(cv2(mp1(cv1(XX))))).shape) ## 이미지를 펼친것 (1D) 
print(d1(flttn(mp2(cv2(mp1(cv1(XX)))))).shape) ## 이미지를 펼친것 (1D) 

(10000, 28, 28, 1)
(10000, 27, 27, 30)
(10000, 13, 13, 30)
(10000, 12, 12, 30)
(10000, 6, 6, 30)
(10000, 1080)
(10000, 10)


- 복잡한거아냐?

`-` 파라메터 비교

In [26]:
net1.summary() ## 23,860

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (32, 784)                 0         
                                                                 
 dense_2 (Dense)             (32, 30)                  23550     
                                                                 
 dense_3 (Dense)             (32, 10)                  310       
                                                                 
Total params: 23,860
Trainable params: 23,860
Non-trainable params: 0
_________________________________________________________________


In [27]:
net2.summary() # 1,149,010

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 500)               392500    
                                                                 
 dense_5 (Dense)             (None, 500)               250500    
                                                                 
 dense_6 (Dense)             (None, 500)               250500    
                                                                 
 dense_7 (Dense)             (None, 500)               250500    
                                                                 
 dense_8 (Dense)             (None, 10)                5010      
                                                                 
Total params: 1,149,010
Trainable params: 1,149,010
No

In [28]:
net3.summary() # 14,590

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 27, 27, 30)        150       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 30)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 12, 12, 30)        3630      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 30)         0         
 2D)                                                             
                                                                 
 flatten_3 (Flatten)         (None, 1080)              0         
                                                                 
 dense_9 (Dense)             (None, 10)               

In [29]:
14590/23860

0.6114836546521375

In [30]:
14590/1149010

0.012697887746842934

## maxpooling

### 테스트 1

In [31]:
m = tf.keras.layers.MaxPool2D()

In [34]:
XXX = tnp.arange(1*4*4*1)
XXX

<tf.Tensor: shape=(16,), dtype=int64, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])>

In [35]:
XXX = XXX.reshape(1,4,4,1) ## 컬러이미지
XXX

<tf.Tensor: shape=(1, 4, 4, 1), dtype=int64, numpy=
array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15]]]])>

In [36]:
XXX.reshape(1,4,4) ## 흑백이미지

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])>

In [38]:
m(XXX)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int64, numpy=
array([[[[ 5],
         [ 7]],

        [[13],
         [15]]]])>

In [39]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[ 5,  7],
        [13, 15]]])>

* 눈치껏 `XXX.reshape(1,4,4)`에서 각각의 `2 x 2`에서 가장 큰 값을 찾아주는 것으로 생각하자.

* 즉, `2 x 2`의 window를 만들고 그 중 가장 기록 후 윈도우를 움직이면서 이 과정을 반복한다.

### 테스트 2

In [40]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])>

In [41]:
m(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=int64, numpy=
array([[[ 7,  9, 11],
        [19, 21, 23],
        [31, 33, 35]]])>

* 윈도우 크기 `2 x 2`는 디폴트 값이다!!

### 테스트 3

In [42]:
m=tf.keras.layers.MaxPool2D(pool_size=(3,3))

In [43]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])>

In [44]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[14, 17],
        [32, 35]]])>

### 테스트 4

In [54]:
m=tf.keras.layers.MaxPool2D(pool_size=(2,2))

In [55]:
XXX = tnp.arange(1*5*5*1).reshape(1,5,5,1)
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])>

* 차원이 안맞는 부분은 버리고 계산한다.

In [56]:
m(XXX).reshape(1,2,2) ## 어? 뒤에 나머지 5행과 5열은 버리고 계산한다....

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[ 6,  8],
        [16, 18]]])>

In [50]:
# ?tf.keras.layers.MaxPool2D

* `padding` 옵션을 `same`으로 주면 남는 차원을 버리지 않음

In [51]:
m=tf.keras.layers.MaxPool2D(pool_size=(2,2),padding="same")

In [53]:
m(XXX).reshape(1,3,3) 

<tf.Tensor: shape=(1, 3, 3), dtype=int64, numpy=
array([[[ 6,  8,  9],
        [16, 18, 19],
        [21, 23, 24]]])>

### 테스트 5

* 관측치가 2개 채널(색)은 흑백

In [57]:
m=tf.keras.layers.MaxPool2D(pool_size=(2,2))

In [59]:
XXX = tnp.arange(2*4*4*1).reshape(2,4,4,1)
XXX.reshape(2,4,4)

<tf.Tensor: shape=(2, 4, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])>

In [60]:
m(XXX).reshape(2,2,2) 

<tf.Tensor: shape=(2, 2, 2), dtype=int64, numpy=
array([[[ 5,  7],
        [13, 15]],

       [[21, 23],
        [29, 31]]])>

### 테스트 6 

In [61]:
XXX = tnp.arange(1*4*4*3).reshape(1,4,4,3)

In [68]:
XXX[:,:,:,0] ## 첫번째 채널

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21],
        [24, 27, 30, 33],
        [36, 39, 42, 45]]])>

In [64]:
m(XXX)

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int64, numpy=
array([[[[15, 16, 17],
         [21, 22, 23]],

        [[39, 40, 41],
         [45, 46, 47]]]])>

In [69]:
m(XXX)[:,:,:,0] ## 첫번째 채널

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[15, 21],
        [39, 45]]])>

## Convolution 2D

`-` 테스트 1

`-` 레이어 생성

In [87]:
cv = tf.keras.layers.Conv2D(1, kernel_size = (2,2))

`-` XXX 생성

In [88]:
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1) ### 4 x 4 픽셀을 가진 이미지 생성
XXX.reshape(1,4,4) 

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

* 아래가 에러가 나는 이유
  * 데이터 타입이 int가 아닌 float이어야한다.
  * 또한 차원을 `XXX.reshape(1,4,4)`로 입력하면 에러가 난다.

In [89]:
cv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[-4.290876 , -4.5067925, -4.722709 ],
        [-5.154542 , -5.3704586, -5.5863748],
        [-6.0182076, -6.234124 , -6.45004  ]]], dtype=float32)>

* 사칙연산, max 이런 형태로 데이터가 변환되서 출력 되는 것이 아닌 것 같음

* 또한, 레이어의 가중치가 랜덤으로 배정되는 것 같음

`-` 코드 정리 + 시드통일

In [93]:
tf.random.set_seed(43052)
cv = tf.keras.layers.Conv2D(1, kernel_size = (2,2))
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)
print(XXX.reshape(1,4,4)) 
print(cv(XXX).reshape(1,3,3))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)
tf.Tensor(
[[[ -4.125754   -5.312817   -6.4998803]
  [ -8.874006  -10.0610695 -11.248133 ]
  [-13.622259  -14.809322  -15.996386 ]]], shape=(1, 3, 3), dtype=float32)


* dense layer를 생각해보면 가중치가 랜덤으로 배정되기 때문에 시드를 고정해주었다.

* weight를 한번 찍어보자

In [94]:
cv.weights

[<tf.Variable 'conv2d_7/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32)>,
 <tf.Variable 'conv2d_7/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [95]:
type(cv.weights) ## 길이가 2인 리스트가 출력

list

In [96]:
cv.weights[0]

<tf.Variable 'conv2d_7/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
array([[[[-0.13014299]],

        [[-0.23927206]]],


       [[[-0.20175874]],

        [[-0.6158894 ]]]], dtype=float32)>

In [100]:
print(XXX.reshape(1,4,4)) 
tf.reshape(cv.weights[0],(2,2))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.13014299, -0.23927206],
       [-0.20175874, -0.6158894 ]], dtype=float32)>

`-` 연산과정

In [104]:
0*-0.13014299 + 1*-0.23927206 + 4*-0.20175874 + 5*-0.6158894 +0 ## 0 은 bias

-4.1257540200000005

In [102]:
print(cv(XXX).reshape(1,3,3))

tf.Tensor(
[[[ -4.125754   -5.312817   -6.4998803]
  [ -8.874006  -10.0610695 -11.248133 ]
  [-13.622259  -14.809322  -15.996386 ]]], shape=(1, 3, 3), dtype=float32)


`-` weight를 변경해보자

In [108]:
cv.get_weights()[0].shape

(2, 2, 1, 1)

In [117]:
w = tnp.array([1/4,1/4,1/4,1/4],dtype=tf.float32).reshape(2,2,1,1)
b = tnp.array([3],dtype=tf.float32)

In [118]:
cv.set_weights([w,b])

In [119]:
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

`w`는 0,1,4,5를 평균내기위한 weight 값으로 설정한 것이다.

In [123]:
cv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 5.5,  6.5,  7.5],
        [ 9.5, 10.5, 11.5],
        [13.5, 14.5, 15.5]]], dtype=float32)>

In [124]:
tnp.mean([0,1,4,5])+3,tnp.mean([1,2,5,6])+3,tnp.mean([2,3,6,7])+3

(<tf.Tensor: shape=(), dtype=float64, numpy=5.5>,
 <tf.Tensor: shape=(), dtype=float64, numpy=6.5>,
 <tf.Tensor: shape=(), dtype=float64, numpy=7.5>)

### Conv 2D 요약

(1) size = (2,2)인 윈도우를 만든다.

(2) XXX에 윈도우를 통과시켜서 (2,2)크기의 `sub XXX`를 얻음, `sub XXX`의 각 원소에 `conv2d.weights[0]`의 각 원소를 `element-wise`하게 곱한다.

(3) (2)의 결과를 모두 더한다.

(4) 위 과정을 `window`를 이동시키면서 반복!

`-` 테스트 2

In [155]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,(3,3))
XXX = tnp.arange(1*5*5*1,dtype=tf.float64).reshape(1,5,5,1)

In [156]:
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]]])>

In [158]:
tf.reshape(cnv.weights[0],(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.08676198, -0.1595147 , -0.13450584],
       [-0.4105929 , -0.38366908,  0.07744962],
       [-0.09255642,  0.4915564 ,  0.20828158]], dtype=float32)>

In [160]:
cnv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 2.7395768 ,  2.2492635 ,  1.7589504 ],
        [ 0.28801066, -0.20230258, -0.6926158 ],
        [-2.1635566 , -2.6538715 , -3.1441827 ]]], dtype=float32)>

In [161]:
tf.reduce_sum(XXX.reshape(1,5,5)[0,:3,:3] * tf.reshape(cnv.weights[0],(3,3)))

<tf.Tensor: shape=(), dtype=float64, numpy=2.739577144384384>

`-` 테스트 3

In [169]:
XXX = tf.constant([[3,3,2,1,0],[0,0,1,3,1],[3,1,2,2,3],[2,0,0,2,2],[2,0,0,0,1]],dtype=tf.float64).reshape(1,5,5,1)
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float64, numpy=
array([[[3., 3., 2., 1., 0.],
        [0., 0., 1., 3., 1.],
        [3., 1., 2., 2., 3.],
        [2., 0., 0., 2., 2.],
        [2., 0., 0., 0., 1.]]])>

In [184]:
_w = tf.constant([[0,1,2],[2,2,0],[0,1,2]],dtype = tf.float64)
_b = tf.constant([0],dtype=tf.float64)

In [186]:
cnv= tf.keras.layers.Conv2D(1, kernel_size = (3,3))

In [187]:
cnv.set_weights([_w,_b])

ValueError: ignored

`-` 테스트 4

In [190]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,kernel_size=(2,2))
XXX 

### `-` 테스트 3,4 다시...

`-` 테스트 5

* 관측치는 고정이고 출력채널이 바뀔 때

In [205]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,kernel_size=(2,2)) ## 출력채널이 1인 경우 값이 1개 나옴 element wise 정확히 알아야한다
XXX = tnp.arange(1*2*2*1,dtype=tf.float64).reshape(1,2,2,1)

In [206]:
print(XXX.reshape(1,2,2))

tf.Tensor(
[[[0. 1.]
  [2. 3.]]], shape=(1, 2, 2), dtype=float64)


In [207]:
cnv(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 1.048703  , -1.0948269 , -0.04476056, -1.7289025 ]]]],
      dtype=float32)>

In [209]:
cnv.weights[0] # (2 x 2)커널의크기 // 1은 XXX의 채널 수 // 4는 con(XXX)의 채널수

<tf.Variable 'conv2d_28/kernel:0' shape=(2, 2, 1, 4) dtype=float32, numpy=
array([[[[-0.08230966, -0.15132892, -0.12760344, -0.38952267]],

        [[-0.36398047,  0.07347518, -0.08780673,  0.46633136]]],


       [[[ 0.19759327, -0.46042526, -0.15406173, -0.34838456]],

        [[ 0.33916563, -0.08248386,  0.11705655, -0.49948823]]]],
      dtype=float32)>

In [214]:
cnv.weights[0][...,0].reshape(2,2) ## conv(XXX)의 첫 번째 채널의 weight 값

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08230966, -0.36398047],
       [ 0.19759327,  0.33916563]], dtype=float32)>

In [217]:
tf.reduce_sum(XXX.reshape(1,2,2) * cnv.weights[0][...,0].reshape(2,2)) ## 이는 Conv 2D를 거쳐 나오는 첫번째 출력 값

<tf.Tensor: shape=(), dtype=float64, numpy=1.0487029552459717>

* 채널을 뻥튀기한다 $\to$ 아무의미없다 그냥 늘리는 것이다 $
\to$ 그냥 파라미터를 많이 써서 뻥튀기하는 것이다.

* 원래 채널은 3개(색깔)지만 그냥 모델을 복잡하게 해서 뻥튀기를 하는 것이다.

`-` 테스트 6

* X의 채널이 여러개고, Conv의 채널도 여러개 일때

In [218]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,kernel_size=(2,2))
XXX = tnp.array([1]*1*2*2*1,dtype=tf.float64).reshape(1,2,2,1)

In [220]:
print(XXX.reshape(1,2,2))

tf.Tensor(
[[[1. 1.]
  [1. 1.]]], shape=(1, 2, 2), dtype=float64)


- 위와같이 `XXX`를 설정하면 `cnv(XXX)`의 결과는 단지 cnv의 `weigth`들의 합이 된다.

In [221]:
cnv(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 0.09046876, -0.6207628 , -0.25241536, -0.7710641 ]]]],
      dtype=float32)>

In [222]:
cnv.weights[0] # (2 x 2)커널의크기 // 1은 XXX의 채널 수 // 4는 con(XXX)의 채널수

<tf.Variable 'conv2d_29/kernel:0' shape=(2, 2, 1, 4) dtype=float32, numpy=
array([[[[-0.08230966, -0.15132892, -0.12760344, -0.38952267]],

        [[-0.36398047,  0.07347518, -0.08780673,  0.46633136]]],


       [[[ 0.19759327, -0.46042526, -0.15406173, -0.34838456]],

        [[ 0.33916563, -0.08248386,  0.11705655, -0.49948823]]]],
      dtype=float32)>

In [227]:
tf.reduce_sum(cnv.weights[0][...,0]) == tf.reduce_sum(XXX.reshape(1,2,2) * cnv.weights[0][...,0].reshape(2,2))

<tf.Tensor: shape=(), dtype=bool, numpy=True>

* 계산결과를 확인하기 쉽게 만든 약간의 트릭

In [234]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,kernel_size=(2,2))
XXX = tnp.array([1]*1*2*2*3,dtype=tf.float64).reshape(1,2,2,3) ## X의 채널 차원 수를 늘림

In [236]:
cnv(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 0.3297621, -0.4498347, -1.0487393, -1.580095 ]]]],
      dtype=float32)>

In [238]:
cnv.weights ## (2 x 2)는 커널 사이즈 // 3은 XXX의 채널 // 4는 conv(xxx) 출력 채널

[<tf.Variable 'conv2d_34/kernel:0' shape=(2, 2, 3, 4) dtype=float32, numpy=
 array([[[[-0.06956434, -0.12789628, -0.10784459, -0.32920673],
          [-0.30761963,  0.06209785, -0.07421023,  0.3941219 ],
          [ 0.16699678, -0.38913035, -0.13020593, -0.29443866]],
 
         [[ 0.28664726, -0.0697116 ,  0.09893084, -0.4221446 ],
          [-0.23161241, -0.16410837, -0.36420006,  0.12424195],
          [-0.14245945,  0.36286396, -0.10751781,  0.1733647 ]]],
 
 
        [[[ 0.02764335,  0.15547717, -0.42024496, -0.31893867],
          [ 0.22414821,  0.3619454 , -0.00282967, -0.3503708 ],
          [ 0.4610079 , -0.17417148,  0.00401336, -0.29777044]],
 
         [[-0.1620284 , -0.42066965, -0.01578814, -0.4240524 ],
          [ 0.37925082,  0.24236053,  0.3949356 , -0.20996472],
          [-0.30264795, -0.28889188, -0.3237777 ,  0.37506342]]]],
       dtype=float32)>,
 <tf.Variable 'conv2d_34/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [239]:
cnv.weights[0][...,0] ### cnv(XXX)의 첫번째 채널을 얻기위해 사용되는 weight값

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.06956434, -0.30761963,  0.16699678],
        [ 0.28664726, -0.23161241, -0.14245945]],

       [[ 0.02764335,  0.22414821,  0.4610079 ],
        [-0.1620284 ,  0.37925082, -0.30264795]]], dtype=float32)>

In [240]:
tf.reduce_sum(cnv.weights[0][...,0]) ## 오 cnv(XXX)의 첫번째 값과 같다. 즉 첫번째 채널의 결과 ## 이거 시험에 안나오니 정리만!!
## 채널이 뻥튀기 될 때 뻥튀기 된 채널이 아무의미가 없고 유의미한 피쳐가 있을 것이라고 기대하는 것이다 즉 그중에 강아지인지, 고양이지인지 그중에 하나만 걸려라의 느낌의 뻥튀기

<tf.Tensor: shape=(), dtype=float32, numpy=0.32976213>

In [245]:
print(tf.reduce_sum(cnv.weights[0][...,1])) ## 두 번째 cnv(XXX)
print(tf.reduce_sum(cnv.weights[0][...,2])) ## 두 번째 cnv(XXX)
print(tf.reduce_sum(cnv.weights[0][...,3])) ## 두 번째 cnv(XXX)

tf.Tensor(-0.44983464, shape=(), dtype=float32)
tf.Tensor(-1.0487392, shape=(), dtype=float32)
tf.Tensor(-1.5800952, shape=(), dtype=float32)


In [249]:
w_red = cnv.weights[0][...,0][...,0] ## X의 입력 채널
w_green = cnv.weights[0][...,0][...,1] ## X의 입력 채널
w_blue = cnv.weights[0][...,0][...,2] ## X의 입력 채널

In [250]:
w_red

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.06956434,  0.28664726],
       [ 0.02764335, -0.1620284 ]], dtype=float32)>

In [253]:
XXX[...,0]*w_red  +  XXX[...,1] * w_green  + XXX[...,2] * w_blue 

<tf.Tensor: shape=(1, 2, 2), dtype=float64, numpy=
array([[[-0.2101872 , -0.08742461],
        [ 0.71279946, -0.08542553]]])>

In [252]:
XXX[...,0] ## X_red

<tf.Tensor: shape=(1, 2, 2), dtype=float64, numpy=
array([[[1., 1.],
        [1., 1.]]])>

* 만약 layer의 acitvation을 relu로 잡으면 음의값은 전부 0으로 바뀐다.

## 텐서플로우를 공부하기 좋은 교재 혹은 참고자료

#### 텐서플로우 교재

`-` 교재1: http://www.kyobobook.co.kr/product/detailViewEng.laf?mallGb=ENG&ejkGb=ENG&barcode=9781838823412
- 장점: 텐서플로우 2.0을 다룬 교재, 기본적 내용을 간략히 소개. 다양한 분야를 커버. 
- 단점: 내용이 조금 산만함 (잘 안읽힘). 코드가 예쁘지 않음. 글을 진짜 못씀. 


`-` 교재2: https://www.amazon.com/Advanced-Deep-Learning-TensorFlow-Keras/dp/1838821651/ref=pd_sbs_sccl_2_2/139-5369471-9501726?pd_rd_w=PLPU2&pf_rd_p=3676f086-9496-4fd7-8490-77cf7f43f846&pf_rd_r=019BZNCP8B6RHXPKXF0T&pd_rd_r=2dea359c-c5d4-4404-86d8-cb1f5f934607&pd_rd_wg=98kmk&pd_rd_i=1838821651&psc=1

- 장점: 코드가 예쁘다. 예제가 잘 구성됨. 참신하다. 내용에 깊이가 있다. 
- 단점: 입문용 내용이 아예 없음

`-` 교재3: 텐서플로 딥러닝 프로그래밍 (김동근/가메출판사) 
- 장점: 한글교재, 그래도 교재구성에 흐름이 있다. 공식문서의 가이드내용도 포함 (대부분은 튜토리얼 수준만 포함) 
- 단점: 공식문서내용 그냥 거의 그대로 베낌. 

#### 공식홈페이지

`-` 튜토리얼: https://www.tensorflow.org/tutorials?hl=ko
- 탭눌러서 초보자~고급 모두 읽어보면 좋다.
- 간단한 모형실습들 제공.
- 대부분의 교재는 튜토리얼의 내용을 베껴서 출판한다. (외국교재도 포함!)

`-` 가이드: https://www.tensorflow.org/guide?hl=ko
- 왜 파이토치가 아니고 텐서플로우를 써야하는가? 에 대한 대답들 
- 모형에 대한 설명보다 프로그램 자체에 대한 이해도를 높여준다. 

`-` API: https://www.tensorflow.org/versions?hl=ko
- tf의 다양한 모듈구조를 확인 
- 파이썬에서 도움말 치면 나오는 것들 + $\alpha$ 
- 교재에서 확인불가능한 아주 디테일한 부분까지 확인가능 

In [ ]:
tf.GradientTape?

Init signature: tf.GradientTape(persistent=False, watch_accessed_variables=True)
Docstring:     
Record operations for automatic differentiation.

Operations are recorded if they are executed within this context manager and
at least one of their inputs is being "watched".

Trainable variables (created by `tf.Variable` or `tf.compat.v1.get_variable`,
where `trainable=True` is default in both cases) are automatically watched.
Tensors can be manually watched by invoking the `watch` method on this context
manager.

For example, consider the function `y = x * x`. The gradient at `x = 3.0` can
be computed as:

>>> x = tf.constant(3.0)
>>> with tf.GradientTape() as g:
...   g.watch(x)
...   y = x * x
>>> dy_dx = g.gradient(y, x)
>>> print(dy_dx)
tf.Tensor(6.0, shape=(), dtype=float32)

GradientTapes can be nested to compute higher-order derivatives. For example,

>>> x = tf.constant(5.0)
>>> with tf.GradientTape() as g:
...   g.watch(x)
...   with tf.GradientTape() as gg:
...     gg.watch(x)


#### 텐서플로우가 아닌 그냥 딥러닝 이론교재 

`-` Deep Learning (이안굿펠로우): https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=171345378
- 장점: 그나마 잘 쓰여진 전통있는 교재, 교수님들 책꽃이에 하나씩 꼽혀있었음. 방대한 내용다룸. 깊이있음. 틀린것 없음. 무료
- 단점: 번역이 쓰레기임. 내용이 너무 어려움. (이해를 하라고 쓴 설명이 아님) 
- 무료제공: https://www.deeplearningbook.org/

`-` 기계학습 (오일석) 
- 장점: 이해가 잘된다. 꽤 넓은 분야를 다룬다. 비교적 간단한 예제로 개념을 설명한다. 

### CNN의 시작: 알렉스넷

`-` 만화: https://wedatalab.tistory.com/71

### 2d convolution 