# (2주차) Tensorflow

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈
- categories: [python]
- hide :false
- published: true
- editor : 전북대학교 통계학과 이강철

# 1주차 복습

## 회귀계수 추정치

* 단순선형회귀의 경우 일반적인 베타계수의 추정치 

$\hat {\beta_0} = \bar y - \beta _1\bar x, \quad \hat {\beta_1} = \frac {S_{xy}} {S_{xx}}$

* 다중 회귀의 경우

$$L=loss =({\bf y}-{\bf X}{\boldsymbol \beta})^\top({\bf y}-{\bf X}{\boldsymbol \beta})$$ 


$$ L= {\bf y}^\top {\bf y} - {\bf y}^\top {\bf X}{\boldsymbol\beta} - {\boldsymbol\beta}^\top {\bf X}^\top {\bf y} + {\boldsymbol\beta}^\top {\bf X}^\top {\bf X} {\boldsymbol\beta}$$

* 위를 미분하면

$$\frac{\partial}{\partial \boldsymbol{\beta}} L = \frac{\partial}{\partial \boldsymbol{\beta}} {\bf y}^\top {\bf y} - \frac{\partial}{\partial \boldsymbol{\beta}} {\bf y}^\top {\bf X}{\boldsymbol\beta} - \frac{\partial}{\partial \boldsymbol{\beta}} {\boldsymbol\beta}^\top {\bf X}^\top {\bf y} + \frac{\partial}{\partial \boldsymbol{\beta}} {\boldsymbol\beta}^\top {\bf X}^\top {\bf X} {\boldsymbol\beta}  $$


 $$\frac{\partial}{\partial \boldsymbol{\beta}} L=- \mathbf{X^{\top}y} - \mathbf{X^{\top}y} + 2\mathbf{X^{\top}X\boldsymbol \beta}$$

따라서

$$\quad \bf{X^{\top}X}\beta
 = \bf{X^{\top}Y}$$

$$\therefore \quad \hat {\beta} = \left(\bf{X^{\top}X}^{-1}\right)XY$$

***

# 2주차 수업시작~~

In [1]:
#collapse-hide
import tensorflow as tf
import numpy as np

# tensorflow의 GPU 연결법

In [ ]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

# tf.constant 

## 예비학습: 중첩리스트 

`-` 리스트

In [5]:
lst = list(range(6))
lst

[0, 1, 2, 3, 4, 5]

In [6]:
lst[-1]

5

`-` 리스트 안에 리스트 생성

In [9]:
lst =[[1,2,],[3,4]]
lst

[[1, 2], [3, 4]]

In [12]:
print(lst[1][0],lst[0][0])

3 1


`-` 위 같은 2차원의 리스트 구조를 행렬로 생각할 수 있다

1  2 \\
3  4

또는

1  \\
2  \\
3  \\
4 

`-`  (4,1) 행렬 느낌의 리스트

In [22]:
lst = [[1],[2],[3],[4]]
lst

[[1], [2], [3], [4]]

In [23]:
np.array(lst)

array([[1],
       [2],
       [3],
       [4]])

`-` (1,4) 행렬 느낌의 리스트

In [24]:
lst = [1,2,3,4]
lst

[1, 2, 3, 4]

In [25]:
np.array(lst)

array([1, 2, 3, 4])


## 변수 선언

### 스칼라 

In [26]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [27]:
tf.constant(3.14) + tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=6.28>

### 벡터

In [31]:
_vector = tf.constant([1,2,3 ])
_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [32]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### 매트릭스 생성

In [34]:
_matrix = tf.constant([[1,0],[0,1]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

### 텐서 == 3차원 이상의 배열

In [36]:
np.array([[[0,1],[1,2]],[[0,1],[1,2]]])

array([[[0, 1],
        [1, 2]],

       [[0, 1],
        [1, 2]]])

In [37]:
tf.constant([[[0,1],[1,2]],[[0,1],[1,2]]])

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[0, 1],
        [1, 2]],

       [[0, 1],
        [1, 2]]], dtype=int32)>

### 타입

In [38]:
type(tf.constant([[[0,1],[1,2]],[[0,1],[1,2]]]))

tensorflow.python.framework.ops.EagerTensor

 `-` 끝에 `EagerTensor` 가 나오는 것을 기억하자

### 인덱싱 

In [39]:
_matrix  = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [40]:
_matrix[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [42]:
_matrix[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [43]:
_matrix[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [44]:
_matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### tf.constant는 불편하다. 

`-` 각 컬럼의 데이터 타입이 전부 동일하여야 한다.

`-` 원소 수정이 불가능함.

In [45]:
 a= tf.constant([1,22,33])
 a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 22, 33], dtype=int32)>

In [47]:
a[0] =11

TypeError: ignored

`-` 묵시적(간접적) 형변환이 불가능하다.

In [48]:
1+3.14

4.140000000000001

In [54]:
tf.constant(1) + tf.constant(3.14)

InvalidArgumentError: ignored

`-` 같은 float 도 안되는 경우가 있음

In [57]:
tf.constant(1.0, dtype= tf.float64) + tf.constant(3.14)

InvalidArgumentError: ignored

### tf.constant $\to$ 넘파이 

In [59]:
np.array(tf.constant(1))

array(1, dtype=int32)

In [60]:
a = tf.constant(3.14)
type(a)

tensorflow.python.framework.ops.EagerTensor

In [61]:
a.numpy()

3.14

## 연산

### 더하기

In [64]:
a = tf.constant([1,2])
b = tf.constant([3,4])
a+b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [65]:
tf.add(a,b) ## 이건 예전버전 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

### 곱하기

`-` 결과가 조금 이상하다. 일반적인 행렬연사이 아니다

In [67]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

`-` but matrix의 곱은

In [68]:
a = tf.constant([[1,0],[0,1]])
b = tf.constant([[5],[7]])
a@b

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

In [ ]:
tf.matmul(a,b) ## 위와 같은 표현

### 역행렬

In [69]:
a = tf.constant([[1,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]], dtype=int32)>

In [70]:
tf.linalg.inv(a)

InvalidArgumentError: ignored

* 위의 경우는 자료가 int 형이여서 안되는 거임 

In [71]:
?tf.constant

* 아래오 같이 자료형을 선언해 주어야함 

In [72]:
a = tf.constant([[1,0],[0,2]],dtype=float)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1. , 0. ],
       [0. , 0.5]], dtype=float32)>

### determinant

In [73]:
a = tf.constant([[1,2],[3,4]],dtype=float)
print(a)
tf.linalg.det(a)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

### Trace

In [74]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

## 형태변환

`-` 1 x 4 행렬을 $\to$  4 x 1 

In [75]:
a = tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [76]:
tf.reshape(a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

`-` 3차원으로도 변경이 가능

In [77]:
tf.reshape(a,(2,2,1))

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

`-` 다차원의 경우 적용

In [81]:
a = tf.constant(list(range(1,13)))
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [82]:
tf.reshape(a,(2,2,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [83]:
tf.reshape(a,(4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

* `-1` 을 기입하면 남은 차원 수를 알아서 기입해줌 `-1` = `?` 라고 생각

In [86]:
tf.reshape(a,(4,-1))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [89]:
b= tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

`-` 다시 일차원으로 되돌림 

In [90]:
tf.reshape(b,-1)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

## 선언고급 

`-` 리스트나, 넘파이로 만들고 output을 tensor로 변경하는 것도 좋은 방법이다.

In [93]:
ㅣ = [1,2,3,4]
tf.constant(np.diag(ㅣ))

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])>

`-` tf.ones, tf.zeros 

In [94]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

`-` tf.linspace(0,1,10)

In [95]:
tf.linspace(0,1,10)

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

## tf.concat 

## tf.stack 

## tf.einsum

# tnp

## tnp 사용방법 (불만해결방법)

#### 선언, 선언고급

#### 타입

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

#### 그렇지만 np.array는 아님 

### tf.Variable

#### 선언 

#### 타입

#### 인덱싱 

#### tf.Variable $\to$ 넘파이 

#### tf.Variable 도 불편하다. 

#### 연산 

#### 형태변환 

#### 선언고급 

#### tf.concat 

#### tf.stack

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함