# (2주차) Tensorflow

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈
- categories: [python]
- hide :false
- published: true
- editor : 전북대학교 통계학과 이강철

# 1주차 복습

## 회귀계수 추정치

* 단순선형회귀의 경우 일반적인 베타계수의 추정치 

$\hat {\beta_0} = \bar y - \beta _1\bar x, \quad \hat {\beta_1} = \frac {S_{xy}} {S_{xx}}$

* 다중 회귀의 경우

$$L=loss =({\bf y}-{\bf X}{\boldsymbol \beta})^\top({\bf y}-{\bf X}{\boldsymbol \beta})$$ 


$$ L= {\bf y}^\top {\bf y} - {\bf y}^\top {\bf X}{\boldsymbol\beta} - {\boldsymbol\beta}^\top {\bf X}^\top {\bf y} + {\boldsymbol\beta}^\top {\bf X}^\top {\bf X} {\boldsymbol\beta}$$

* 위를 미분하면

$$\frac{\partial}{\partial \boldsymbol{\beta}} L = \frac{\partial}{\partial \boldsymbol{\beta}} {\bf y}^\top {\bf y} - \frac{\partial}{\partial \boldsymbol{\beta}} {\bf y}^\top {\bf X}{\boldsymbol\beta} - \frac{\partial}{\partial \boldsymbol{\beta}} {\boldsymbol\beta}^\top {\bf X}^\top {\bf y} + \frac{\partial}{\partial \boldsymbol{\beta}} {\boldsymbol\beta}^\top {\bf X}^\top {\bf X} {\boldsymbol\beta}  $$


 $$\frac{\partial}{\partial \boldsymbol{\beta}} L=- \mathbf{X^{\top}y} - \mathbf{X^{\top}y} + 2\mathbf{X^{\top}X\boldsymbol \beta}$$

따라서

$$\quad \bf{X^{\top}X}\beta
 = \bf{X^{\top}Y}$$

$$\therefore \quad \hat {\beta} = \left(\bf{X^{\top}X}^{-1}\right)XY$$

***

# 2주차 수업시작~~

In [1]:
#collapse-hide
import tensorflow as tf
import numpy as np

# tensorflow의 GPU 연결법

In [ ]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

# tf.constant 

## 예비학습: 중첩리스트 

`-` 리스트

In [5]:
lst = list(range(6))
lst

[0, 1, 2, 3, 4, 5]

In [6]:
lst[-1]

5

`-` 리스트 안에 리스트 생성

In [9]:
lst =[[1,2,],[3,4]]
lst

[[1, 2], [3, 4]]

In [12]:
print(lst[1][0],lst[0][0])

3 1


`-` 위 같은 2차원의 리스트 구조를 행렬로 생각할 수 있다

1  2 \\
3  4

또는

1  \\
2  \\
3  \\
4 

`-`  (4,1) 행렬 느낌의 리스트

In [22]:
lst = [[1],[2],[3],[4]]
lst

[[1], [2], [3], [4]]

In [23]:
np.array(lst)

array([[1],
       [2],
       [3],
       [4]])

`-` (1,4) 행렬 느낌의 리스트

In [24]:
lst = [1,2,3,4]
lst

[1, 2, 3, 4]

In [25]:
np.array(lst)

array([1, 2, 3, 4])


## 변수 선언

### 스칼라 

In [26]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [27]:
tf.constant(3.14) + tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=6.28>

### 벡터

In [31]:
_vector = tf.constant([1,2,3 ])
_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [32]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### 매트릭스 생성

In [34]:
_matrix = tf.constant([[1,0],[0,1]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

### 텐서 == 3차원 이상의 배열

In [36]:
np.array([[[0,1],[1,2]],[[0,1],[1,2]]])

array([[[0, 1],
        [1, 2]],

       [[0, 1],
        [1, 2]]])

In [37]:
tf.constant([[[0,1],[1,2]],[[0,1],[1,2]]])

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[0, 1],
        [1, 2]],

       [[0, 1],
        [1, 2]]], dtype=int32)>

### 타입

In [38]:
type(tf.constant([[[0,1],[1,2]],[[0,1],[1,2]]]))

tensorflow.python.framework.ops.EagerTensor

 `-` 끝에 `EagerTensor` 가 나오는 것을 기억하자

### 인덱싱 

In [39]:
_matrix  = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [40]:
_matrix[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [42]:
_matrix[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [43]:
_matrix[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [44]:
_matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### tf.constant는 불편하다. 

`-` 각 컬럼의 데이터 타입이 전부 동일하여야 한다.

`-` 원소 수정이 불가능함.

In [45]:
 a= tf.constant([1,22,33])
 a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 22, 33], dtype=int32)>

In [47]:
a[0] =11

TypeError: ignored

`-` 묵시적(간접적) 형변환이 불가능하다.

In [48]:
1+3.14

4.140000000000001

In [54]:
tf.constant(1) + tf.constant(3.14)

InvalidArgumentError: ignored

`-` 같은 float 도 안되는 경우가 있음

In [57]:
tf.constant(1.0, dtype= tf.float64) + tf.constant(3.14)

InvalidArgumentError: ignored

### tf.constant $\to$ 넘파이 

In [59]:
np.array(tf.constant(1))

array(1, dtype=int32)

In [60]:
a = tf.constant(3.14)
type(a)

tensorflow.python.framework.ops.EagerTensor

In [61]:
a.numpy()

3.14

## 연산

### 더하기

In [64]:
a = tf.constant([1,2])
b = tf.constant([3,4])
a+b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [65]:
tf.add(a,b) ## 이건 예전버전 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

### 곱하기

`-` 결과가 조금 이상하다. 일반적인 행렬연사이 아니다

In [67]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

`-` but matrix의 곱은

In [68]:
a = tf.constant([[1,0],[0,1]])
b = tf.constant([[5],[7]])
a@b

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

In [ ]:
tf.matmul(a,b) ## 위와 같은 표현

### 역행렬

In [69]:
a = tf.constant([[1,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]], dtype=int32)>

In [70]:
tf.linalg.inv(a)

InvalidArgumentError: ignored

* 위의 경우는 자료가 int 형이여서 안되는 거임 

In [71]:
?tf.constant

* 아래오 같이 자료형을 선언해 주어야함 

In [72]:
a = tf.constant([[1,0],[0,2]],dtype=float)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1. , 0. ],
       [0. , 0.5]], dtype=float32)>

### determinant

In [73]:
a = tf.constant([[1,2],[3,4]],dtype=float)
print(a)
tf.linalg.det(a)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

### Trace

In [74]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

## 형태변환

`-` 1 x 4 행렬을 $\to$  4 x 1 

In [75]:
a = tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [76]:
tf.reshape(a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

`-` 3차원으로도 변경이 가능

In [77]:
tf.reshape(a,(2,2,1))

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

`-` 다차원의 경우 적용

In [81]:
a = tf.constant(list(range(1,13)))
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [82]:
tf.reshape(a,(2,2,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [83]:
tf.reshape(a,(4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

* `-1` 을 기입하면 남은 차원 수를 알아서 기입해줌 `-1` = `?` 라고 생각

In [86]:
tf.reshape(a,(4,-1))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [89]:
b= tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

`-` 다시 일차원으로 되돌림 

In [90]:
tf.reshape(b,-1)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

## 선언고급 

`-` 리스트나, 넘파이로 만들고 output을 tensor로 변경하는 것도 좋은 방법이다.

In [93]:
ㅣ = [1,2,3,4]
tf.constant(np.diag(ㅣ))

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])>

`-` tf.ones, tf.zeros 

In [94]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

`-` tf.linspace(0,1,10)

In [95]:
tf.linspace(0,1,10)

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

## tf.concat 

In [110]:
a = tf.constant([1,2])
b = tf.constant([3,4])
a,b

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [97]:
a = tf.constant([[1],[2]])
b = tf.constant([[3],[4]])
a,b

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [2]], dtype=int32)>, <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [4]], dtype=int32)>)

In [99]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [102]:
a = tf.constant([[1],[2]])
b = tf.constant([[3],[4]])
a,b

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [2]], dtype=int32)>, <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [4]], dtype=int32)>)

In [103]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [109]:
a = tf.constant([1,2])
b = tf.constant([3,4])
a,b

tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [108]:
a = tf.constant([[1,2]]) 
b = tf.constant([[3,4]])
a,b

tf.concat([a,b],axis=0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### 차원 수 증가 

* `(2,3,4,5)` concat `(2,3,4,5)` => `(4,3,4,5)`

In [117]:
a=tf.reshape(tf.constant(range(120)),(2,3,4,5))
b= -a

In [115]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 3, 4, 5), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]]],


       [[[  60,   61,   62,   63,   64],
         [  65,   66,   67,   68,   69],
         [  70,   71,   72,   73,   74],
         [  75,   76,   77,   78,   79]],

        [[  80,   81,   82,   83,   84],
         [  85,   86,   87,   88,   89],
         [  90,   91,   92,   93,   94],
         [  95,   96,   97,   98,   99]],

        [[ 100,  101,  102,  103,  104],
         [ 105,  106,  107,  108,  109],
         [ 110,  111,  112,  113, 

* `(2,3,4,5)` concat `(2,3,4,5)` => `(2,6,4,5)`

In [120]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 6, 4, 5), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]],

        [[   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -

* `(2,3,4,5)` concat `(2,3,4,5)` => `(2,3,8,5)`

In [121]:
tf.concat([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 8, 5), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19],
         [   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39],
         [ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59],
         [ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -54],
 

* `(2,3,4,5)` concat `(2,3,4,5)` => `(2,3,4,10)`

In [122]:
tf.concat([a,b],axis=3)

<tf.Tensor: shape=(2, 3, 4, 10), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4,    0,   -1,   -2,   -3,   -4],
         [   5,    6,    7,    8,    9,   -5,   -6,   -7,   -8,   -9],
         [  10,   11,   12,   13,   14,  -10,  -11,  -12,  -13,  -14],
         [  15,   16,   17,   18,   19,  -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24,  -20,  -21,  -22,  -23,  -24],
         [  25,   26,   27,   28,   29,  -25,  -26,  -27,  -28,  -29],
         [  30,   31,   32,   33,   34,  -30,  -31,  -32,  -33,  -34],
         [  35,   36,   37,   38,   39,  -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44,  -40,  -41,  -42,  -43,  -44],
         [  45,   46,   47,   48,   49,  -45,  -46,  -47,  -48,  -49],
         [  50,   51,   52,   53,   54,  -50,  -51,  -52,  -53,  -54],
         [  55,   56,   57,   58,   59,  -55,  -56,  -57,  -58,  -59]]],


       [[[  60,   61,   62,   63,   64,  -60,  -61,  -62,  -63,  -64],
         [  65, 

* 아래와 같은 방법도 있긴하나 난 안할래

In [125]:
tf.concat([a,b],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 10), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4,    0,   -1,   -2,   -3,   -4],
         [   5,    6,    7,    8,    9,   -5,   -6,   -7,   -8,   -9],
         [  10,   11,   12,   13,   14,  -10,  -11,  -12,  -13,  -14],
         [  15,   16,   17,   18,   19,  -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24,  -20,  -21,  -22,  -23,  -24],
         [  25,   26,   27,   28,   29,  -25,  -26,  -27,  -28,  -29],
         [  30,   31,   32,   33,   34,  -30,  -31,  -32,  -33,  -34],
         [  35,   36,   37,   38,   39,  -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44,  -40,  -41,  -42,  -43,  -44],
         [  45,   46,   47,   48,   49,  -45,  -46,  -47,  -48,  -49],
         [  50,   51,   52,   53,   54,  -50,  -51,  -52,  -53,  -54],
         [  55,   56,   57,   58,   59,  -55,  -56,  -57,  -58,  -59]]],


       [[[  60,   61,   62,   63,   64,  -60,  -61,  -62,  -63,  -64],
         [  65, 

### 차원을 한번 줄여보자

* `(4,)` -> `(8,)`

In [127]:
a=tf.constant([1,2,3,4])
b=-a
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [136]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1,  2,  3,  4, -1, -2, -3, -4], dtype=int32)>

* `(4,)` -> `(4,2)`

`-` 에러가 뜬다

In [145]:
tf.concat([a,b],axis=1)

InvalidArgumentError: ignored

## tf.stack 

* `(4,)` -> `(4,2)`

In [143]:
a=tf.constant([1,2,3,4])
b=-a
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [147]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2],
       [ 3, -3],
       [ 4, -4]], dtype=int32)>

## tf.einsum

# tnp

`-` 텐서만들기가 너무 힘듬

In [150]:
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior() ## tnf 를 numpy 처럼 사용할 수 있도록 해줌

## tnp 사용방법 (불만해결방법)

`-` `int` 와 `float` 을 더할 수 있음

In [158]:
tnp.array([1,2,3]) + tnp.array([1.0,2.0,3.0]) 

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

* 심지어

In [160]:
tnp.array(1) + tnp.array([1.0,2.0,3.0]) 

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [161]:
tnp.array([1,2,3]) + tf.constant([1.0,2.0,3.0]) 

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

In [163]:
a = tnp.diag([1,2,3])
type(a)

tensorflow.python.framework.ops.EagerTensor

In [165]:
a.min(),a.max()

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3>)

In [175]:
a.reshape(9,1)

<tf.Tensor: shape=(9, 1), dtype=int64, numpy=
array([[1],
       [0],
       [0],
       [0],
       [2],
       [0],
       [0],
       [0],
       [3]])>

### 선언, 선언고급

In [176]:
np.random.randn(5)

array([-1.79271696, -0.17190837,  1.01536417,  0.10096996,  0.6384037 ])

In [177]:
tnp.random.randn(5)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 0.68371875, -0.77886642, -0.78283853, -1.91862598, -0.36602414])>

### 타입

In [178]:
type(tnp.random.randn(5))

tensorflow.python.framework.ops.EagerTensor

### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

`-` 묵시적 형변환이 가능해짐

`-` 메소드를 쓸 수 있음.


### 그렇지만 np.array는 아님 

* 여전히 값을 바꾸는 것은 허용하지 않는다.

In [180]:
 a = tf.constant([1,2,3])

In [181]:
a[0]=11

TypeError: ignored

### tf.Variable

#### 선언 

#### 타입

#### 인덱싱 

#### tf.Variable $\to$ 넘파이 

#### tf.Variable 도 불편하다. 

#### 연산 

#### 형태변환 

#### 선언고급 

#### tf.concat 

#### tf.stack

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함