# import

In [112]:
import tensorflow as tf 
import tensorflow.experimental.numpy as tnp 
import numpy as np

In [113]:
tnp.experimental_enable_numpy_behavior()

In [114]:
tf.random.set_seed(202150256)

# 데이터 생성

In [117]:
image = tf.constant([0,0,0,1,1,1]*6,dtype=tf.float64).reshape(1,6,6,1)

In [118]:
image.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=float64, numpy=
array([[[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]]])>

# Conv2D

In [119]:
cv = tf.keras.layers.Conv2D(1, kernel_size = (2,2))

In [121]:
cv(image).reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float32, numpy=
array([[[0.       , 0.       , 0.9023603, 0.1632362, 0.1632362],
        [0.       , 0.       , 0.9023603, 0.1632362, 0.1632362],
        [0.       , 0.       , 0.9023603, 0.1632362, 0.1632362],
        [0.       , 0.       , 0.9023603, 0.1632362, 0.1632362],
        [0.       , 0.       , 0.9023603, 0.1632362, 0.1632362]]],
      dtype=float32)>

In [122]:
tf.reshape(cv.weights[0],(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.16480297,  0.14897054],
       [-0.57432115,  0.7533898 ]], dtype=float32)>

# weight 설정

In [123]:
w = tnp.array([-1,1,-1,1],dtype=tf.float32).reshape(2,2,1,1)
b = tnp.array([0],dtype=tf.float32)

In [124]:
cv.set_weights([w,b])

In [125]:
tf.reshape(cv.weights[0],(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.,  1.],
       [-1.,  1.]], dtype=float32)>

In [85]:
cv.weights[1]

<tf.Variable 'conv2d_9/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

# 결과 확인

In [126]:
cv(image).reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float32, numpy=
array([[[0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.]]], dtype=float32)>